### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by jakeprins** [kalwabed/nextwind#5]
Consider changing the name of the project. I assume this project is started or inspired by [NextWind](  https://github.com/jakeprins/nextwind), which is ok, but using the same name might be confusing for people searching for the template.

**Comment by kalwabed** [comment]
Thanks, Jake, but sorry your assumption about me being inspired by yours isn't quite right, even before that I didn't even know you had [NextWind](https://github.com/jakeprins/nextwind).
I think people know what they are looking for, and the difference between yours and mine is quite far, maybe just the same name, but the content is certainly more awesome yours, right?

**Comment by jakeprins** [comment]
Oh sorry, man. Because we both use some of the same setups I made those assumptions too quickly. I guess it's just a coincidence then.
